name: Book checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run script
        env:
          EFITNESS_LOGIN: ${{ secrets.EFITNESS_LOGIN }}
          EFITNESS_PASSWORD: ${{ secrets.EFITNESS_PASSWORD }}
        run: python book.py

      - name: Upload debug
        uses: actions/upload-artifact@v4
        with:
          name: login-debug
          path: output/

